# Generated by Django 5.0 on 2025-02-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
